// constants.ts
import { RoomType, Material, CuratedRoom, MaterialCategory } from './types';
import { defaultProfileFor, PhysicalProfile } from './services/materialProfile';

export const MATERIAL_CATEGORIES: Exclude<MaterialCategory, 'all'>[] = [
  'tile',
  'sheet',
  'carpet',
  'wallpaper',
  'paint',
  'stone',
  'wood',
  'plaster',
  'metal',
  'fabric',
];

export const ROOM_TYPES: RoomType[] = [
  'Living Room',
  'Bedroom',
  'Kitchen',
  'Dining Room',
  'Office / Study',
  'Bathroom',
  'Penthouse Lounge',
];

export const CURATED_ROOMS: CuratedRoom[] = [
  {
    id: 'minimalist-living',
    title: 'Modern Minimalist Salon',
    roomType: 'Living Room',
    style: 'Warm Organic Minimalist',
    thumbnail: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=400&q=80',
    fullImage: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=85',
    detectedDefaults: [
      { name: 'Feature Accent Wall', category: 'Surfaces & Walls', description: 'Primary focal wall behind lounge seating' },
      { name: 'Hardwood Oak Flooring', category: 'Flooring', description: 'Wide-plank primary surface floor' },
      { name: 'Minimalist Sectional Sofa', category: 'Furniture', description: 'Modular low-profile upholstered seating' },
      { name: 'Sculptural Coffee Table', category: 'Furniture', description: 'Organic geometric low center table' },
      { name: 'Recessed Architectural Ceiling', category: 'Architectural', description: 'Flush minimalist ceiling plane' },
    ],
  },
  {
    id: 'nordic-master-bedroom',
    title: 'Sanctuary Master Suite',
    roomType: 'Bedroom',
    style: 'Scandinavian Zen',
    thumbnail: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=400&q=80',
    fullImage: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=85',
    detectedDefaults: [
      { name: 'Headboard Feature Wall', category: 'Surfaces & Walls', description: 'Vertical acoustic or plaster focal wall' },
      { name: 'Low Platform Bedframe', category: 'Furniture', description: 'Solid perimeter bed structure' },
      { name: 'Linear Parquet Floor', category: 'Flooring', description: 'Herringbone timber floor' },
      { name: 'Floating Bedside Credenza', category: 'Cabinetry', description: 'Minimal wall-hung nightstands' },
      { name: 'Pendant Ambient Lighting', category: 'Decor', description: 'Suspended architectural luminaire' },
    ],
  },
  {
    id: 'culinary-marble-kitchen',
    title: 'Monolithic Island Kitchen',
    roomType: 'Kitchen',
    style: 'Contemporary Haute',
    thumbnail: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=400&q=80',
    fullImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85',
    detectedDefaults: [
      { name: 'Waterfall Kitchen Island', category: 'Surfaces & Walls', description: 'Massive monolithic central counter' },
      { name: 'Seamless Full-Height Cabinetry', category: 'Cabinetry', description: 'Integrated floor-to-ceiling cabinet facade' },
      { name: 'Backsplash & Niche', category: 'Surfaces & Walls', description: 'Slab stone splashback wall' },
      { name: 'Architectural Bar Stools', category: 'Furniture', description: 'Minimalist counter seating' },
      { name: 'Large-Format Floor Tile', category: 'Flooring', description: 'Matte stone flooring panels' },
    ],
  },
  {
    id: 'penthouse-dining-room',
    title: 'Architectural Dining Pavilion',
    roomType: 'Dining Room',
    style: 'Contemporary Luxury',
    thumbnail: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=400&q=80',
    fullImage: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1600&q=85',
    detectedDefaults: [
      { name: 'Statement Dining Tabletop', category: 'Furniture', description: 'Primary monumental dining slab' },
      { name: 'Sculpted Dining Chairs', category: 'Furniture', description: 'Ergonomic upholstered dining suite' },
      { name: 'Venetian Plaster Perimeter Wall', category: 'Surfaces & Walls', description: 'Textured wall with natural light wash' },
      { name: 'Timber Plank Floor', category: 'Flooring', description: 'Warm continuous hardwood' },
      { name: 'Architectural Chandelier', category: 'Architectural', description: 'Linear overhead design light' },
    ],
  },
  {
    id: 'executive-atelier-office',
    title: 'Curator Executive Study',
    roomType: 'Office / Study',
    style: 'Modern Brutalist Warmth',
    thumbnail: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=400&q=80',
    fullImage: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1600&q=85',
    detectedDefaults: [
      { name: 'Executive Desk Surface', category: 'Furniture', description: 'Main workstation writing surface' },
      { name: 'Bespoke Bookshelf Millwork', category: 'Cabinetry', description: 'Floor-to-ceiling recessed joinery' },
      { name: 'Concrete Plaster Wall', category: 'Surfaces & Walls', description: 'Industrial architectural feature plane' },
      { name: 'Lounge Armchair', category: 'Furniture', description: 'Architectural accent leather chair' },
      { name: 'Chevron Oak Flooring', category: 'Flooring', description: 'Classic patterned hardwood' },
    ],
  },
];

// Seed catalog without physical data; profiles come from category defaults below
// Textures: Poly Haven scans (CC0), downloaded locally by `npm run assets:fetch`; sizes are
// the scans' measured real-world dimensions.
const SEED_MATERIALS: Array<Omit<Material, keyof PhysicalProfile> & Partial<PhysicalProfile>> = [
  // --- Natural Stone ---
  {
    id: 'calacatta_viola',
    tenantId: null,
    name: 'White Veined Marble',
    category: 'stone',
    finishType: 'Honed',
    colorTone: 'Warm White & Grey Vein',
    description: 'White marble with soft grey veining, honed to a low sheen.',
    thumbnail: '/textures/marble_01_thumb.png',
    albedoUrl: '/textures/marble_01.jpg',
    normalUrl: '/textures/marble_01_nor_gl.jpg',
    roughnessUrl: '/textures/marble_01_rough.jpg',
    realWidthMm: 1500,
    realHeightMm: 1500,
    repeatMode: 'seamless',
    roughness: 0.35,
    metallic: 0,
  },
  {
    id: 'nero_marquina',
    tenantId: null,
    name: 'Terrazzo Tiles',
    category: 'stone',
    finishType: 'Polished',
    colorTone: 'Grey Aggregate',
    description: 'Classic terrazzo with mixed stone aggregate set in grey cement.',
    thumbnail: '/textures/terrazzo_tiles_thumb.png',
    albedoUrl: '/textures/terrazzo_tiles.jpg',
    normalUrl: '/textures/terrazzo_tiles_nor_gl.jpg',
    roughnessUrl: '/textures/terrazzo_tiles_rough.jpg',
    realWidthMm: 2000,
    realHeightMm: 2000,
    repeatMode: 'seamless',
    roughness: 0.3,
    metallic: 0,
  },
  {
    id: 'roman_travertine',
    tenantId: null,
    name: 'Sandstone Block Wall',
    category: 'stone',
    finishType: 'Split Face',
    colorTone: 'Warm Sand',
    description: 'Large dressed sandstone blocks with natural mortar joints.',
    thumbnail: '/textures/large_sandstone_blocks_01_thumb.png',
    albedoUrl: '/textures/large_sandstone_blocks_01.jpg',
    normalUrl: '/textures/large_sandstone_blocks_01_nor_gl.jpg',
    roughnessUrl: '/textures/large_sandstone_blocks_01_rough.jpg',
    realWidthMm: 3000,
    realHeightMm: 3000,
    repeatMode: 'seamless',
    roughness: 0.85,
    metallic: 0,
  },
  {
    id: 'patagonia_quartzite',
    tenantId: null,
    name: 'Granite Wall Tiles',
    category: 'stone',
    finishType: 'Honed',
    colorTone: 'Speckled Grey',
    description: 'Honed granite wall tiles with fine mineral speckle.',
    thumbnail: '/textures/granite_tile_03_thumb.png',
    albedoUrl: '/textures/granite_tile_03.jpg',
    normalUrl: '/textures/granite_tile_03_nor_gl.jpg',
    roughnessUrl: '/textures/granite_tile_03_rough.jpg',
    realWidthMm: 1802,
    realHeightMm: 1802,
    repeatMode: 'seamless',
    roughness: 0.4,
    metallic: 0,
  },
  // --- Wood ---
  {
    id: 'fluted_white_oak',
    tenantId: null,
    name: 'White Oak Veneer',
    category: 'wood',
    finishType: 'Matte Oil',
    colorTone: 'Pale Natural Oak',
    description: 'Crown-cut white oak veneer with straight, even grain.',
    thumbnail: '/textures/white_oak_veneer_thumb.png',
    albedoUrl: '/textures/white_oak_veneer.jpg',
    normalUrl: '/textures/white_oak_veneer_nor_gl.jpg',
    roughnessUrl: '/textures/white_oak_veneer_rough.jpg',
    realWidthMm: 500,
    realHeightMm: 500,
    repeatMode: 'seamless',
    roughness: 0.6,
    metallic: 0,
  },
  {
    id: 'smoked_walnut_chevron',
    tenantId: null,
    name: 'Herringbone Parquet',
    category: 'wood',
    finishType: 'Satin Lacquer',
    colorTone: 'Honey Oak',
    description: 'Oak herringbone parquet with a satin lacquered finish.',
    thumbnail: '/textures/herringbone_parquet_thumb.png',
    albedoUrl: '/textures/herringbone_parquet.jpg',
    normalUrl: '/textures/herringbone_parquet_nor_gl.jpg',
    roughnessUrl: '/textures/herringbone_parquet_rough.jpg',
    realWidthMm: 3400,
    realHeightMm: 3400,
    repeatMode: 'seamless',
    roughness: 0.4,
    metallic: 0,
  },
  {
    id: 'ebonized_ash',
    tenantId: null,
    name: 'Black Oak Veneer',
    category: 'wood',
    finishType: 'Matte',
    colorTone: 'Ebony Black',
    description: 'Ebonised oak veneer with the grain still visible.',
    thumbnail: '/textures/black_oak_veneer_thumb.png',
    albedoUrl: '/textures/black_oak_veneer.jpg',
    normalUrl: '/textures/black_oak_veneer_nor_gl.jpg',
    roughnessUrl: '/textures/black_oak_veneer_rough.jpg',
    realWidthMm: 1000,
    realHeightMm: 1000,
    repeatMode: 'seamless',
    roughness: 0.6,
    metallic: 0,
  },
  // --- Plaster & Concrete ---
  {
    id: 'venetian_plaster',
    tenantId: null,
    name: 'White Lime Plaster',
    category: 'plaster',
    finishType: 'Troweled Matte',
    colorTone: 'Chalk White',
    description: 'Hand-troweled lime plaster with a soft, cloudy finish.',
    thumbnail: '/textures/white_plaster_02_thumb.png',
    albedoUrl: '/textures/white_plaster_02.jpg',
    normalUrl: '/textures/white_plaster_02_nor_gl.jpg',
    roughnessUrl: '/textures/white_plaster_02_rough.jpg',
    realWidthMm: 1000,
    realHeightMm: 1000,
    repeatMode: 'seamless',
    roughness: 0.9,
    metallic: 0,
  },
  {
    id: 'raw_microcement',
    tenantId: null,
    name: 'Smooth Microcement',
    category: 'plaster',
    finishType: 'Sealed Matte',
    colorTone: 'Warm Concrete Grey',
    description: 'Seamless microcement with a sealed, smooth finish.',
    thumbnail: '/textures/smooth_concrete_floor_thumb.png',
    albedoUrl: '/textures/smooth_concrete_floor.jpg',
    normalUrl: '/textures/smooth_concrete_floor_nor_gl.jpg',
    roughnessUrl: '/textures/smooth_concrete_floor_rough.jpg',
    realWidthMm: 2000,
    realHeightMm: 2000,
    repeatMode: 'seamless',
    roughness: 0.7,
    metallic: 0,
  },
  // --- Metals ---
  {
    id: 'champagne_brass',
    tenantId: null,
    name: 'Brushed Steel Plate',
    category: 'metal',
    finishType: 'Brushed Satin',
    colorTone: 'Cool Steel Grey',
    description: 'Large-format brushed steel cladding plate.',
    thumbnail: '/textures/metal_plate_02_thumb.png',
    albedoUrl: '/textures/metal_plate_02.jpg',
    normalUrl: '/textures/metal_plate_02_nor_gl.jpg',
    roughnessUrl: '/textures/metal_plate_02_rough.jpg',
    realWidthMm: 2000,
    realHeightMm: 2000,
    repeatMode: 'seamless',
    roughness: 0.35,
    metallic: 0.9,
  },
  {
    id: 'patinated_bronze',
    tenantId: null,
    name: 'Patinated Metal',
    category: 'metal',
    finishType: 'Weathered Patina',
    colorTone: 'Verdigris & Rust',
    description: 'Weathered metal with a mottled verdigris patina.',
    thumbnail: '/textures/green_metal_rust_thumb.png',
    albedoUrl: '/textures/green_metal_rust.jpg',
    normalUrl: '/textures/green_metal_rust_nor_gl.jpg',
    roughnessUrl: '/textures/green_metal_rust_rough.jpg',
    realWidthMm: 1000,
    realHeightMm: 1000,
    repeatMode: 'seamless',
    roughness: 0.6,
    metallic: 0.5,
  },
  // --- Textiles ---
  {
    id: 'ivory_boucle',
    tenantId: null,
    name: 'Natural Teddy Bouclé',
    category: 'fabric',
    finishType: 'Curled Loop Pile',
    colorTone: 'Oatmeal',
    description: 'Soft curled-loop bouclé in a natural oatmeal tone.',
    thumbnail: '/textures/curly_teddy_natural_thumb.png',
    albedoUrl: '/textures/curly_teddy_natural.jpg',
    normalUrl: '/textures/curly_teddy_natural_nor_gl.jpg',
    roughnessUrl: '/textures/curly_teddy_natural_rough.jpg',
    realWidthMm: 336,
    realHeightMm: 331,
    repeatMode: 'seamless',
    roughness: 0.95,
    metallic: 0,
  },
  {
    id: 'belgian_linen',
    tenantId: null,
    name: 'Rough Linen',
    category: 'fabric',
    finishType: 'Washed',
    colorTone: 'Natural Flax',
    description: 'Slubby, open-weave linen in natural flax.',
    thumbnail: '/textures/rough_linen_thumb.png',
    albedoUrl: '/textures/rough_linen.jpg',
    normalUrl: '/textures/rough_linen_nor_gl.jpg',
    roughnessUrl: '/textures/rough_linen_rough.jpg',
    realWidthMm: 271,
    realHeightMm: 271,
    repeatMode: 'seamless',
    roughness: 0.9,
    metallic: 0,
  },
  {
    id: 'cognac_saddle_leather',
    tenantId: null,
    name: 'Brown Leather',
    category: 'fabric',
    finishType: 'Waxed Aniline',
    colorTone: 'Saddle Brown',
    description: 'Full-grain brown leather with a natural pebble.',
    thumbnail: '/textures/brown_leather_thumb.png',
    albedoUrl: '/textures/brown_leather.jpg',
    normalUrl: '/textures/brown_leather_nor_gl.jpg',
    roughnessUrl: '/textures/brown_leather_rough.jpg',
    realWidthMm: 400,
    realHeightMm: 400,
    repeatMode: 'seamless',
    roughness: 0.5,
    metallic: 0,
  },
  // --- Tile ---
  {
    id: 'carrara_bianco_porcelain',
    tenantId: null,
    name: 'Long White Tiles',
    category: 'tile',
    finishType: 'Gloss Glaze',
    colorTone: 'Bright White',
    description: 'Elongated white glazed tiles laid in a running bond.',
    thumbnail: '/textures/long_white_tiles_thumb.png',
    albedoUrl: '/textures/long_white_tiles.jpg',
    normalUrl: '/textures/long_white_tiles_nor_gl.jpg',
    roughnessUrl: '/textures/long_white_tiles_rough.jpg',
    realWidthMm: 1270,
    realHeightMm: 1270,
    repeatMode: 'seamless',
    roughness: 0.2,
    metallic: 0,
  },
  {
    id: 'terracotta_maroon_quarry',
    tenantId: null,
    name: 'Terracotta Floor Tiles',
    category: 'tile',
    finishType: 'Matte Fired Clay',
    colorTone: 'Terracotta Red',
    description: 'Hand-made terracotta floor tiles with lime grout.',
    thumbnail: '/textures/terracotta_floor_tiles_thumb.png',
    albedoUrl: '/textures/terracotta_floor_tiles.jpg',
    normalUrl: '/textures/terracotta_floor_tiles_nor_gl.jpg',
    roughnessUrl: '/textures/terracotta_floor_tiles_rough.jpg',
    realWidthMm: 2080,
    realHeightMm: 2080,
    repeatMode: 'seamless',
    roughness: 0.8,
    metallic: 0,
  },
  {
    id: 'mosaic_harlequin_tile',
    tenantId: null,
    name: 'Marble Mosaic Tiles',
    category: 'tile',
    finishType: 'Honed',
    colorTone: 'White & Grey Marble',
    description: 'Small-format marble mosaic on a mesh backing.',
    thumbnail: '/textures/marble_mosaic_tiles_thumb.png',
    albedoUrl: '/textures/marble_mosaic_tiles.jpg',
    normalUrl: '/textures/marble_mosaic_tiles_nor_gl.jpg',
    roughnessUrl: '/textures/marble_mosaic_tiles_rough.jpg',
    realWidthMm: 2000,
    realHeightMm: 2000,
    repeatMode: 'seamless',
    roughness: 0.4,
    metallic: 0,
  },
  // --- Sheet Vinyl ---
  {
    id: 'cirrus_grey_sheet_vinyl',
    tenantId: null,
    name: 'Brown Linoleum Sheet',
    category: 'sheet',
    finishType: 'Low Sheen',
    colorTone: 'Chestnut Brown',
    description: 'Roll-format linoleum sheet flooring in a mottled chestnut.',
    thumbnail: '/textures/linoleum_brown_thumb.png',
    albedoUrl: '/textures/linoleum_brown.jpg',
    normalUrl: '/textures/linoleum_brown_nor_gl.jpg',
    roughnessUrl: '/textures/linoleum_brown_rough.jpg',
    realWidthMm: 2000,
    realHeightMm: 2000,
    repeatMode: 'seamless',
    roughness: 0.5,
    metallic: 0,
  },
  // --- Carpet ---
  {
    id: 'dove_grey_looped_carpet',
    tenantId: null,
    name: 'Wool Herringbone Carpet',
    category: 'carpet',
    finishType: 'Flat Weave',
    colorTone: 'Grey Herringbone',
    description: 'Flat-woven wool carpet with a herringbone pattern.',
    thumbnail: '/textures/poly_wool_herringbone_thumb.png',
    albedoUrl: '/textures/poly_wool_herringbone.jpg',
    normalUrl: '/textures/poly_wool_herringbone_nor_gl.jpg',
    roughnessUrl: '/textures/poly_wool_herringbone_rough.jpg',
    realWidthMm: 270,
    realHeightMm: 276,
    repeatMode: 'seamless',
    roughness: 0.95,
    metallic: 0,
  },
  {
    id: 'ash_grey_plush_carpet',
    tenantId: null,
    name: 'Grey Wool Plush Carpet',
    category: 'carpet',
    finishType: 'Plush Pile',
    colorTone: 'Heather Grey',
    description: 'Dense wool-blend plush pile in heather grey.',
    thumbnail: '/textures/caban_thumb.png',
    albedoUrl: '/textures/caban.jpg',
    normalUrl: '/textures/caban_nor_gl.jpg',
    roughnessUrl: '/textures/caban_rough.jpg',
    realWidthMm: 274,
    realHeightMm: 273,
    repeatMode: 'seamless',
    roughness: 0.95,
    metallic: 0,
  },
  // --- Wallpaper ---
  {
    id: 'cobalt_bloom_wallpaper',
    tenantId: null,
    name: 'Patterned Textile Wallcovering',
    category: 'wallpaper',
    finishType: 'Printed Textile',
    colorTone: 'Multi-Colour Pattern',
    description: 'Printed textile wallcovering with a repeating pattern.',
    thumbnail: '/textures/fabric_pattern_05_thumb.png',
    albedoUrl: '/textures/fabric_pattern_05.jpg',
    normalUrl: '/textures/fabric_pattern_05_nor_gl.jpg',
    roughnessUrl: '/textures/fabric_pattern_05_rough.jpg',
    realWidthMm: 500,
    realHeightMm: 500,
    repeatMode: 'seamless',
    roughness: 0.85,
    metallic: 0,
  },
  // --- Paint ---
  {
    id: 'curated_palette_matte_paint',
    tenantId: null,
    name: 'Painted Plaster Wall',
    category: 'paint',
    finishType: 'Matte Emulsion',
    colorTone: 'Soft White',
    description: 'Matte emulsion over a hand-finished plaster wall.',
    thumbnail: '/textures/painted_plaster_wall_thumb.png',
    albedoUrl: '/textures/painted_plaster_wall.jpg',
    normalUrl: '/textures/painted_plaster_wall_nor_gl.jpg',
    roughnessUrl: '/textures/painted_plaster_wall_rough.jpg',
    realWidthMm: 2000,
    realHeightMm: 2000,
    repeatMode: 'seamless',
    roughness: 0.85,
    metallic: 0,
  },
];

export const MATERIALS: Material[] = SEED_MATERIALS.map((m) => ({
  ...defaultProfileFor(m.category, `${m.finishType} ${m.description}`),
  ...m,
}));
