import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Mirrors the frontend's offline default catalog (repo-root constants.ts MATERIALS,
// all tenantId: null). IDs match so the live and offline defaults are the same records.
const DEFAULT_MATERIALS = [
  {
    id: 'calacatta_viola',
    name: 'Calacatta Viola Marble',
    category: 'stone',
    finishType: 'Honed Silk Finish',
    colorTone: 'Ivory & Deep Cabernet',
    description: 'Dramatic deep purple and wine-hued veining on milky honed Italian marble.',
    thumbnail: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(74, 30, 48, 0.25)',
  },
  {
    id: 'nero_marquina',
    name: 'Nero Marquina Black',
    category: 'stone',
    finishType: 'Satin Polished',
    colorTone: 'Obsidian & Pure Calcite',
    description: 'Intense black Spanish marble intersected with crisp white mineral streaks.',
    thumbnail: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(18, 18, 20, 0.38)',
  },
  {
    id: 'roman_travertine',
    name: 'Navona Roman Travertine',
    category: 'stone',
    finishType: 'Open-Pore Matte',
    colorTone: 'Warm Sandstone & Alabaster',
    description: 'Timeless Roman sedimented limestone with linear fissures and tactile warmth.',
    thumbnail: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(214, 196, 170, 0.22)',
  },
  {
    id: 'patagonia_quartzite',
    name: 'Patagonia Quartzite',
    category: 'stone',
    finishType: 'Mirror Glaze',
    colorTone: 'Translucent Amber & Smoke',
    description: 'Exotic gemstone rock featuring dramatic crystal quartz clusters and feldspar.',
    thumbnail: 'https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(184, 150, 110, 0.28)',
  },
  {
    id: 'fluted_white_oak',
    name: 'Fluted Architectural Oak',
    category: 'wood',
    finishType: 'Matte Oil Wax',
    colorTone: 'Natural Pale Honey',
    description: 'Sculptural vertical reeded white oak delivering rhythmic shadow and soft acoustic diffusion.',
    thumbnail: 'https://images.unsplash.com/photo-1533090161767-e6ffed986b88?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(197, 160, 115, 0.25)',
  },
  {
    id: 'smoked_walnut_chevron',
    name: 'Smoked Walnut Chevron',
    category: 'wood',
    finishType: 'Hand-Rubbed Lustre',
    colorTone: 'Espresso & Dark Caramel',
    description: 'Rich European walnut timber with rich figuring and balanced dark warmth.',
    thumbnail: 'https://images.unsplash.com/photo-1546484396-fb3fc6f95f98?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(64, 45, 34, 0.32)',
  },
  {
    id: 'ebonized_ash',
    name: 'Ebonized Japanese Ash',
    category: 'wood',
    finishType: 'Wire-Brushed Matte',
    colorTone: 'Charcoal Black',
    description: 'Deep black stained grain where natural wood texture remains strikingly tactile.',
    thumbnail: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(25, 26, 30, 0.36)',
  },
  {
    id: 'venetian_plaster',
    name: 'Italian Venetian Plaster',
    category: 'plaster',
    finishType: 'Troweled Marble Dust',
    colorTone: 'Warm Bone White',
    description: 'Layered artisan lime stucco that diffuses natural daylight with soft luminosity.',
    thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(235, 230, 222, 0.2)',
  },
  {
    id: 'raw_microcement',
    name: 'Warm Architectural Microcement',
    category: 'plaster',
    finishType: 'Seamless Matte Seal',
    colorTone: 'Dove Grey & Mineral Taupe',
    description: 'Jointless contemporary polymer cement with gentle cloudy industrial character.',
    thumbnail: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(160, 155, 148, 0.22)',
  },
  {
    id: 'champagne_brass',
    name: 'Brushed Champagne Brass',
    category: 'metal',
    finishType: 'Directional Satin',
    colorTone: 'Muted Pale Gold',
    description: 'Refined architectural metal with low specular reflection and subtle golden warmth.',
    thumbnail: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(212, 175, 105, 0.28)',
  },
  {
    id: 'patinated_bronze',
    name: 'Burnished Sculptural Bronze',
    category: 'metal',
    finishType: 'Acid-Etched Dark Patina',
    colorTone: 'Deep Umber & Copper',
    description: 'Living metal finish with depth, heritage undertones, and velvet finish.',
    thumbnail: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(100, 70, 50, 0.3)',
  },
  {
    id: 'ivory_boucle',
    name: 'Ivory Cashmere Bouclé',
    category: 'fabric',
    finishType: 'Curled Loop Weave',
    colorTone: 'Oatmeal & Pearl',
    description: 'Ultra-tactile nubby wool loop textile with cozy Scandinavian comfort.',
    thumbnail: 'https://images.unsplash.com/photo-1584589167171-541ce45f1eea?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(242, 238, 230, 0.25)',
  },
  {
    id: 'belgian_linen',
    name: 'Raw Belgian Flax Linen',
    category: 'fabric',
    finishType: 'Enzyme Washed',
    colorTone: 'Natural Sand Flax',
    description: 'Heavily textured organic flax woven in Flanders with relaxed organic elegance.',
    thumbnail: 'https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(215, 203, 185, 0.22)',
  },
  {
    id: 'cognac_saddle_leather',
    name: 'Saddle Cognac Leather',
    category: 'fabric',
    finishType: 'Aniline Waxed',
    colorTone: 'Warm Chestnut Cognac',
    description: 'Supple full-grain Italian hide that develops rich patina and character over time.',
    thumbnail: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(160, 90, 45, 0.32)',
  },
  {
    id: 'carrara_bianco_porcelain',
    name: 'Carrara Bianco Porcelain Tile',
    category: 'tile',
    finishType: 'Polished Porcelain',
    colorTone: 'Soft White & Grey Veining',
    description: 'Large-format porcelain tile with a marble-inspired veined finish, ideal for kitchens, bathrooms, and high-traffic floors.',
    thumbnail: 'https://images.unsplash.com/photo-1656646523907-97b094c7e63a?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(240, 240, 238, 0.2)',
  },
  {
    id: 'terracotta_maroon_quarry',
    name: 'Terracotta Maroon Quarry Tile',
    category: 'tile',
    finishType: 'Matte Fired Clay',
    colorTone: 'Deep Maroon & Rust',
    description: 'Traditional fired-clay quarry tile with a rich maroon tone, suited to rustic kitchens, patios, and entryways.',
    thumbnail: 'https://images.unsplash.com/photo-1547414857-c9f61632b250?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(120, 40, 40, 0.28)',
  },
  {
    id: 'mosaic_harlequin_tile',
    name: 'Mosaic Harlequin Tile',
    category: 'tile',
    finishType: 'Glazed Mosaic',
    colorTone: 'Multicolor Jewel Tones',
    description: 'Small-format glazed mosaic tile in a playful multicolor pattern, ideal for feature walls and backsplashes.',
    thumbnail: 'https://images.unsplash.com/photo-1458682625221-3a45f8a844c7?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(120, 90, 160, 0.22)',
  },
  {
    id: 'cirrus_grey_sheet_vinyl',
    name: 'Cirrus Grey Resilient Sheet Vinyl',
    category: 'sheet',
    finishType: 'Seamless Resilient Sheet',
    colorTone: 'Cool Concrete Grey',
    description: 'Waterproof roll-format sheet vinyl with a smooth concrete-look finish, ideal for low-maintenance kitchens and bathrooms.',
    thumbnail: 'https://images.unsplash.com/photo-1598171182339-b24dd64241a6?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(150, 155, 158, 0.22)',
  },
  {
    id: 'dove_grey_looped_carpet',
    name: 'Dove Grey Looped Carpet',
    category: 'carpet',
    finishType: 'Cut-Loop Pile',
    colorTone: 'Dove Grey',
    description: 'Durable cut-loop wall-to-wall carpet in a versatile neutral grey, suited to bedrooms and living spaces.',
    thumbnail: 'https://images.unsplash.com/photo-1653025428643-a8fcf26ffb91?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(170, 170, 175, 0.2)',
  },
  {
    id: 'ash_grey_plush_carpet',
    name: 'Ash Grey Plush Carpet',
    category: 'carpet',
    finishType: 'Plush Pile',
    colorTone: 'Ash Grey',
    description: 'Soft plush-pile carpet with a dense underfoot feel, suited to bedrooms and quiet living spaces.',
    thumbnail: 'https://images.unsplash.com/photo-1671624760664-8946fd3037a3?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(150, 150, 155, 0.22)',
  },
  {
    id: 'cobalt_bloom_wallpaper',
    name: 'Cobalt Bloom Patterned Wallpaper',
    category: 'wallpaper',
    finishType: 'Printed Non-Woven',
    colorTone: 'Cobalt Blue & Crimson',
    description: 'Bold printed non-woven wallpaper with a saturated red-and-blue pattern, ideal for a feature wall statement.',
    thumbnail: 'https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(90, 60, 140, 0.22)',
  },
  {
    id: 'curated_palette_matte_paint',
    name: 'Curated Palette Matte Paint',
    category: 'paint',
    finishType: 'Matte Emulsion',
    colorTone: 'Custom Swatch Selection',
    description: 'Premium matte emulsion wall paint, sampled here across a curated palette — select a swatch tone to preview on your walls.',
    thumbnail: 'https://images.unsplash.com/photo-1677110497046-96b550bb0853?auto=format&fit=crop&w=300&q=80',
    renderOverlayTone: 'rgba(180, 170, 150, 0.2)',
  },
];

async function main() {
  for (const material of DEFAULT_MATERIALS) {
    await prisma.material.upsert({
      where: { id: material.id },
      create: { ...material, tenantId: null },
      update: { ...material, tenantId: null },
    });
  }
  console.log(`Seeded ${DEFAULT_MATERIALS.length} shared default materials.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
